### ISSUE TITLE
Participant role is not getting added!

### ISSUE THREAD

**Issue by pacorain** [houseofmisfits/weeping-willow#11]
Here is the output from logs.

```
  File "/usr/src/app/houseofmisfits/weeping_willow/modules/event_module.py", line 77, in add_participant_role,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/discord.py-1.3.1-py3.8.egg/discord/client.py", line 312, in _run_event,
    await coro(*args, **kwargs),
  File "/usr/src/app/houseofmisfits/weeping_willow/client.py", line 89, in on_message,
    await self.add_participant_role(message.author),
  File "/usr/src/app/houseofmisfits/weeping_willow/modules/event_module.py", line 73, in process_participant,
    if await triggered_fn(message):,
    await user.add_roles(await self.get_participant_role()),
  File "/usr/local/lib/python3.8/site-packages/discord.py-1.3.1-py3.8.egg/discord/member.py", line 641, in add_roles,
    await req(guild_id, user_id, role.id, reason=reason),
AttributeError: 'NoneType' object has no attribute 'id',
Ignoring exception in on_message
```

**Comment by pacorain** [comment]
I'm so dumb.

The participant role ID config, and the actual role ID, were set respectively to:
`6794859917103659562`
`679485991710359562`

Somehow, an extra 6 got thrown in there.

**Comment by pacorain** [comment]
I've confirmed it's working when using the production credentials on my machine, I am going to rebuild weeping willow master to close the database port once more and get Weeping Willow back up and running on the server.
